services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: teste
      MARIADB_DATABASE: omp_teste
      MARIADB_PASSWORD: teste
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10


  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mariadb:
        - condition: service_healthy


volumes:
  mariadb_data:
